[package]
name = "df-share"
version = "0.1.1"
edition = "2021"
description = "secret sharing"
license = "MIT"

[dependencies]
ring = "0.16"
aes-gcm = "0.10"
rand = "0.8.5"
sha2 = "0.10.8"

serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
